name: Jobs

on:
  push:

jobs:
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - run: sleep 15
  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - run: sleep 15
  deploy-job:
    name: deploy-job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build output
        run: echo ${{ needs.build-job.outputs.build-output }}




  
  build-job:
    outputs:
      buile-output: ${{ steps.buildStep.outputs.buildOut }}
    name: build job
    runs-on: ubuntu-latest
    container:
      image: oven/bun:slim
    steps:
      - name: define output variable
        id: buildStep
        run: |
          bunver=$(bun --version)
          echo "buildOut=$bunver" >> "$GITHUB_OUTPUT"
